Update README and topics description - Closes #333
LiskHQ/lisk-core pull request #366
Opened 2020-09-08 10:31 UTC by shuse2

### What was the problem?

This PR resolves #333 

### How was it solved?

- Update README to reflect current structure
- Add topics description in package json, so it will show correct information

### How was it tested?

- check README
- `./bin/run` and check description

2020-09-08 11:16 UTC, pablitovicente commented on README.md
> +In order to start a Lisk Core node in a background process, we recommend to use process management tool, such as [PM2](https://pm2.keymetrics.io/).
```suggestion
In order to start a Lisk Core node as a background process, we recommend to use a process management tool, such as [PM2](https://pm2.keymetrics.io/).
```

2020-09-08 11:17 UTC, pablitovicente approved these changes

2020-09-09 07:39 UTC, ManuGowda requested changes

2020-09-09 09:05 UTC, shuse2 commented on docs/commands/blockchain.md
> +  -o, --output=output    [default: /Users/shuse2/Documents/10_lisk/lisk-core] Directory path to specify where snapshot
Auto generated with default... will fix 😢

2020-09-09 11:09 UTC, ManuGowda approved these changes

2020-09-09 11:48 UTC, merged