Add flags to enable monitoring and report misbehaviour plugins - Closes #397
LiskHQ/lisk-core pull request #403
Opened 2020-10-26 08:28 UTC by ManuGowda

### What was the problem?

This PR resolves #397 

### How was it solved?

- Added monitoring and report misbehavior plugin related flags

### How was it tested?

- Updated unit test

2020-10-26 10:10 UTC, shuse2 requested changes
just one minor typing, but LGTM

2020-10-26 10:10 UTC, shuse2 commented on src/commands/start.ts
> +const setPluginConfig = (config: any, flags: any): void => {
prefer not to use `any`

2020-10-26 11:11 UTC, nazarhussain approved these changes

2020-10-27 08:55 UTC, shuse2 approved these changes

2020-10-27 08:55 UTC, merged