Rename enable-ipc to api-ipc - Closes #410
LiskHQ/lisk-core pull request #424
Opened 2020-11-23 13:23 UTC by shuse2

### What was the problem?

This PR resolves #410 

### How was it solved?

With breaking change of SDK https://github.com/LiskHQ/lisk-sdk/issues/5965, config is updated.
Also, name of the flag is now `api-ipc`

### How was it tested?

Start node with `--api-ipc` flag and see if `./bin/run node:info` works

2020-11-23 16:11 UTC, nazarhussain requested changes
In reference to this change, this config does not have any effect. As the IPC is always enabled as of now. We need to add some authentication over IPC and provide some nonce as configuration if user want to use IPC.

2020-11-23 16:11 UTC, nazarhussain commented on config/alphanet/config.json
> +		"port": 8080
Why do we need to provide port in IPC case?

2020-11-24 10:12 UTC, nazarhussain approved these changes

2020-11-24 11:15 UTC, mitsuaki-u approved these changes

2020-11-24 11:16 UTC, merged