Add forging info command to show the forging information - Closes #445
LiskHQ/lisk-core pull request #452
Opened 2020-12-08 14:29 UTC by shuse2

### What was the problem?

This PR resolves #445 

### How was it solved?

- Add forging info command to provide information on locally running node

### How was it tested?
- Added unit test
- run devnet/betanet node and execute below
```
./bin/run forging:info
```

2020-12-08 14:49 UTC, Incede requested changes

2020-12-08 14:49 UTC, Incede commented on src/commands/forging/info.ts
> +	];
```suggestion
	static examples = ['forging:info',];
```
I think this will fix the failing format test.

2020-12-08 14:58 UTC, Incede commented on src/commands/forging/info.ts
> +	];
maybe a good idea to also have example with flags `-d` & `--pretty`

2020-12-08 15:31 UTC, Incede approved these changes

2020-12-09 09:03 UTC, nazarhussain requested changes

2020-12-09 09:03 UTC, nazarhussain commented on src/commands/forging/info.ts
> +		const info = await this._client.invoke('app:getForgingStatus');
As the internal actions is `forgingStatus` why not we have command as well `forging:status`?

2020-12-09 10:21 UTC, Incede commented on src/commands/forging/info.ts
> +		const info = await this._client.invoke('app:getForgingStatus');
I think it would be nice to have 2 commands `forging:info`  which gives an overview like "number of active & standby delegates, round status, next forgers, current block height" and `forging:status` which shows the details about individual forgers "maxHeightPreviouslyForged, maxHeightPreVoted, forgedBlocks" and so on.

2020-12-09 11:02 UTC, nazarhussain approved these changes

2020-12-09 12:16 UTC, merged