Generate forging config for given passphrase, password and hash-onion parameters - Closes #434
LiskHQ/lisk-core pull request #459
Opened 2020-12-29 12:57 UTC by ManuGowda

### What was the problem?

This PR resolves #434 

### How was it solved?

- This command enables delegates to generate forging delegate config with
address, hashOnion and encryptedPassphrase details for given password and passphrase

### How was it tested?

2021-01-04 10:44 UTC, Incede commented on src/commands/forging/config.ts
> +	];
I think we should have the `pretty` flag too

2021-01-04 10:57 UTC, Incede commented on src/commands/forging/config.ts
> +
Again, if we have the `pretty` flag we should check for it here, otherwise skip this check

2021-01-04 10:57 UTC, Incede commented on src/commands/forging/config.ts
> +
I think every example should atleast contain `'forging:config --passphrase your_passphrase --password your_password'` since `passphrase` & `password` are mandatory flags

2021-01-04 10:57 UTC, Incede commented on src/commands/forging/config.ts
> +	static examples = [
same here `'forging:config --passphrase your_passphrase --password your_password --count=1000000 --distance=2000 --output /tmp/forging_config.json'`

2021-01-04 10:57 UTC, Incede commented on src/commands/forging/config.ts
> +	static description = 'Generate delegate forging config for given passphrase and password.';
maybe can add 1 more example with `--pretty`

2021-01-04 10:57 UTC, Incede commented on src/commands/forging/config.ts
> +import { cryptography, validator } from 'lisk-sdk';
Maybe import all the required functions from `cryptography` like this `import { generateHashOnionSeed, hashOnion, getAddressFromPassphrase, } from '@liskhq/lisk-cryptography';` to be more concise.

2021-01-04 11:17 UTC, Incede reviewed
Since we have unit test for `forging:status` command, maybe can have the same here as well

2021-01-04 11:57 UTC, ManuGowda commented on src/commands/forging/config.ts
> +
I have added example with passphrase & password flags and without them(prompt). It's ideal that a user can use prompt for both passphrase & password, which is more secure than using them as flags.

2021-01-04 11:59 UTC, ManuGowda commented on src/commands/forging/config.ts
> +	static examples = [
again i have 4 examples provided so, we don't have to provide every example imo, if it is the case then we have to fix most of the commands.

2021-01-04 12:00 UTC, ManuGowda commented on src/commands/forging/config.ts
> +import { cryptography, validator } from 'lisk-sdk';
cryptography is not the direct dependency, so its better to use `lisk-sdk`.

2021-01-04 16:25 UTC, Incede commented on src/commands/forging/config.ts
> +		'forging:config, forging:config --password your_password, forging:config --passphrase your_passphrase --password your_password',
I think needs to be re-formatted to `'forging:config', 'forging:config --password your_password',` for the examples to show in seperate lines

2021-01-04 16:41 UTC, Incede approved these changes

2021-01-05 11:50 UTC, shuse2 requested changes

2021-01-05 11:50 UTC, shuse2 commented on src/commands/forging/config.ts
> +			fs.writeJSONSync(output, { address, encryptedPassphrase, hashOnion });
write is not considering the `pretty`

2021-01-05 13:51 UTC, shuse2 approved these changes

2021-01-05 13:51 UTC, merged