Add genesis-block download command - Closes #470
LiskHQ/lisk-core pull request #489
Opened 2021-04-27 12:13 UTC by nazarhussain

### What was the problem?

This PR resolves #470

### How was it solved?

- Created command to download genesis block 

### How was it tested?

- Run unit tests
- For testing locally compress a genesis block file and then use `npx http-serve .` to serve that file and use its url in the command

2021-04-27 13:12 UTC, shuse2 requested changes

2021-04-27 13:12 UTC, shuse2 commented on src/commands/start.ts
> +		if (!genesisBlockExists && ['mainnet', 'testnet'].includes(flags.network)) {
i think it would be nice if it downloads from the remote automatically as described in the issue. Also, u can call the genesis-block:download command here

2021-04-27 13:12 UTC, shuse2 commented on src/utils/commons.ts
> +	if (url && url.search(RELEASE_URL) >= 0) {
```suggestion
	if (url && url.search(SNAPSHOT_URL) >= 0) {
```

2021-04-27 13:21 UTC, shuse2 commented on src/commands/genesis-block/download.ts
> +			genesisBlockPath = join(process.cwd(), 'genesis_block.json');
dataPath has default value, so this will never happen?

2021-04-27 13:21 UTC, shuse2 commented on src/commands/genesis-block/download.ts
> +			genesisBlockPath = getDefaultNetworkConfigFilesPath(network).genesisBlockFilePath;
this points to the `package/config` where the devnet/betanet genesis block exist
It should use the `getNetworkConfigFilesPath` instead

2021-04-28 08:44 UTC, nazarhussain commented on src/commands/genesis-block/download.ts
> +			genesisBlockPath = join(process.cwd(), 'genesis_block.json');
I don't see default value for dataPath in the flags definition.

2021-04-28 08:53 UTC, nazarhussain commented on src/commands/start.ts
> +		if (!genesisBlockExists && ['mainnet', 'testnet'].includes(flags.network)) {
Done

2021-04-28 14:13 UTC, mitsuaki-u approved these changes
LGTM minor comment

2021-04-28 14:13 UTC, mitsuaki-u commented on test/commands/genesis-block/download.spec.ts
> +	// const SNAPSHOT_URL = 'https://downloads.lisk.io/lisk/mainnet/blockchain.db.tar.gz';
Remove  comments?

2021-04-29 13:14 UTC, shuse2 approved these changes

2021-04-29 15:23 UTC, merged