Update Lisk Core docker image settings
LiskHQ/lisk-core pull request #500
Opened 2021-06-15 09:16 UTC by fchavant

### What was the problem?

> We decided to disable all plugins by default, e.g.
>
> - lisk-framework-http-api-plugin
> - lisk-framework-forger-plugin
> - lisk-framework-monitor-plugin
> - lisk-framework-report-misbehavior-plugin
>
> We need to document how users can enable said plugins in the docker image README.

### How was it solved?

Remove `docker-compose.*.yml` files, update `README.md`.

### How was it tested?

Following the `README.md`'s instructions.

2021-06-15 09:26 UTC, Nazgolze commented on docker/Makefile
> +	podman build --build-arg REGISTRY_URL=https://npm.lisk.io --build-arg NODEJS_VERSION=$(shell cat ../.nvmrc ) --build-arg CORE_VERSION=$(CORE_VERSION) -t=lisk/core:$(CORE_VERSION) .
Was this one intentional?

2021-06-15 09:28 UTC, fchavant commented on docker/Makefile
> +	podman build --build-arg REGISTRY_URL=https://npm.lisk.io --build-arg NODEJS_VERSION=$(shell cat ../.nvmrc ) --build-arg CORE_VERSION=$(CORE_VERSION) -t=lisk/core:$(CORE_VERSION) .
Nope, good catch.

2021-06-15 13:17 UTC, Nazgolze requested changes
Dockerfile is still trying to pull in coldstart.sh

2021-06-15 14:07 UTC, Nazgolze requested changes
Aside from the one suggested change, there have been some tabs introduced into the README. And with that, I think I've hit the bottom of the barrel and check everything :+1:

2021-06-15 16:18 UTC, Nazgolze approved these changes

2021-06-16 07:09 UTC, shuse2 commented
@fchavant can you branch off from `release/3.0.0` so that we can include this in the testnet release?

2021-06-16 07:55 UTC, ManuGowda approved these changes

2021-06-16 07:55 UTC, ManuGowda commented on docker/README.md
> +Note: podman can be used. Simply replace occurences of `docker` with `podman` or `alias docker=podman`.
maybe link to podman? if someone doesn't know what it is or wants to install before replacing the occurrences?

2021-06-16 07:55 UTC, ManuGowda commented on docker/README.md
> +Note: podman can be used. Simply replace occurences of `docker` with `podman` or `alias docker=podman`.
```suggestion
Note: podman can be used. Simply replace occurrences of `docker` with `podman` or `alias docker=podman`.
```

2021-06-17 07:39 UTC, shuse2 approved these changes

2021-06-17 07:51 UTC, merged