Add --use-status-values for forging:enable - Closes #539
LiskHQ/lisk-core pull request #549
Opened 2021-09-30 11:58 UTC by ManuGowda

### What was the problem?

This PR resolves #539 , #544, #533

### How was it solved?

- Removed unwanted scripts
- Added new flag to use status values
- Added warning to inform users about overwriting forging information

### How was it tested?

- Added new tests, updated old tests

2021-09-30 12:12 UTC, ManuGowda commented on src/commands/forging/enable.ts
> +						'Do you want to overwrite the forging config? If you provide incorrect forging information you can be punished.',
@Tschakki please check with Chris and get a nice text here, this needs improvement 🙏🏼 .

2021-09-30 12:13 UTC, ManuGowda commented on src/commands/forging/enable.ts
> +						message: 'Do you want to use these values to enable forging?',
same here too, if we can improve the sentence

2021-09-30 13:43 UTC, Tschakki requested changes

2021-09-30 13:43 UTC, Tschakki commented on src/commands/forging/enable.ts
> +			if (answer === 'no') {
In what scenario would one want to set the `ovewrite` flag?

Also, we sometimes use the word `override` and sometimes `overwrite` in our code, imho we should decide for one version and use it consistantly to avoid confusion.

Also, it looks to me like replying `yes` to the question has no further effect? So why would you set this flag?

2021-09-30 13:43 UTC, Tschakki commented on src/commands/forging/enable.ts
> +				overwrite: flags.overwrite,
what is used her, if `overwrite` flag isn't set?

2021-09-30 13:53 UTC, Tschakki requested changes

2021-09-30 13:53 UTC, Tschakki commented on src/commands/forging/enable.ts
> +			if (!flags['yes'] && forgerInfo) {
The use of this `yes` flag is a little strange to me, because it makes only sens to be used together with the flag `use-state-values`. Maybe it's better to introduce a new flag for this, something like `auto-use-status-values`

2021-09-30 16:09 UTC, ManuGowda commented on src/commands/forging/enable.ts
> +				overwrite: flags.overwrite,
default false, if flag specified its true.

2021-09-30 16:09 UTC, ManuGowda commented on src/commands/forging/enable.ts
> +			if (!flags['yes'] && forgerInfo) {
@shuse2 what do you think about this approach? one flag is enough here.

2021-09-30 16:09 UTC, ManuGowda commented on src/commands/forging/enable.ts
> +			if (answer === 'no') {
could you please create an issue in SDK, Core, Docs for `override` vs `overwrite` usage?

2021-10-01 09:57 UTC, Tschakki approved these changes
Made some small suggestions for the messages, otherwise LGTM

2021-10-01 09:57 UTC, Tschakki commented on src/commands/forging/enable.ts
> +						'Do you want to overwrite the forging config? If you provide incorrect forging information you can be punished.',
```suggestion
						'CAUTION: Do you really want to overwrite the forging config? If you provide incorrect forging information you will be punished.',
```

2021-10-01 11:32 UTC, MichalTuleja approved these changes
LGTM 👍

2021-10-04 08:06 UTC, shuse2 commented on src/commands/forging/enable.ts
> +			if (!flags['yes'] && forgerInfo) {
i think `--yes` is fine here. I would avoid to use `auto` for this sensitive information

2021-10-04 11:57 UTC, shuse2 requested changes

2021-10-04 11:57 UTC, shuse2 commented on src/commands/forging/enable.ts
> +				});
Here if the delegate is in the config, but never forged, it will return `{ address: 'xxx' }`.
Therefore, it should be initialized with `0` in that case

2021-10-04 11:57 UTC, shuse2 commented on src/commands/forging/enable.ts
> +		if (flags['use-status-values'] && (height || maxHeightPreviouslyForged || maxHeightPrevoted)) {
`0` is also `falsy` here

2021-10-04 16:51 UTC, shuse2 requested changes

2021-10-04 16:51 UTC, shuse2 commented on src/commands/forging/enable.ts
> +	value !== null && value !== undefined && value >= 0;
```
const isZeroAndAbove = (value: unknown): boolean =>
	typeof value === 'number' && value >= 0;
```

2021-10-04 16:51 UTC, shuse2 commented on src/commands/forging/enable.ts
> +					maxHeightPreviouslyForged: forgerInfo.maxHeightPreviouslyForged ?? 0,
i think it's safer to reassign the initial values, and print and send in below so that we can avoid mistake

2021-10-04 18:14 UTC, shuse2 approved these changes

2021-10-05 07:01 UTC, merged