Prepare Lisk Core to use Lisk SDK 6.0.0 - Closes #582
LiskHQ/lisk-core pull request #584
Opened 2022-02-08 09:31 UTC by ManuGowda

### What was the problem?

This PR resolves #582

### How was it solved?

- Updated Lisk SDK to use canary version e.g 5.2.2-alpha.31164
- Updated application instantiation
- Removed HTTP API Plugin
- Updated devnet, alphabet genesis block
- Updated devnet, alphabet application config (generator, naming changes, etc..)

### How was it tested?

- npm install --registry https://npm.lisk.com
- npm run build
- ./bin/run start -n devnet

2022-02-09 09:21 UTC, nagdahimanshu requested changes
Don't we need to update the relevant `md` files in the same issue? (For example, we removed `HTTP API Plugin` but it still exists in the options for the start command `lisk-core/docs/commands/start.md`)

2022-02-09 09:21 UTC, nagdahimanshu commented on src/base_ipc.ts
>  			transaction.assetID as number,
Shouldn't it be?
```suggestion
			transaction.commandID as number,
```

2022-02-09 09:21 UTC, nagdahimanshu commented on config/alphanet/config.json
> +				"assetID": 0,
```suggestion
				"CommandID": 0,
```

2022-02-09 09:21 UTC, nagdahimanshu commented on config/devnet/config.json
> +				"assetID": 0,
Same for this:
```suggestion
				"commandID": 0,
```

2022-02-09 11:26 UTC, sameersubudhi commented
@ManuGowda The following documents still require cleanup concerning the `--enable-http-api-plugin`, `--http-api-plugin-host` and `--http-api-plugin-port` flags. Please search for `http-api` throughout the codebase to find them all (12 occurrences in 4 files listed below).

> - README.md
> - docker/README.md
> - docs/commands/start.md
> - test/scripts/README.md

Similarly for `assetID` mentions in the following files:
> - config/betanet/config.json
> - config/mainnet/config.json
> - config/testnet/config.json
> - docs/commands/transaction.md
> - test/scripts/utils/transactions/create.ts

2022-02-09 13:39 UTC, sameersubudhi approved these changes

2022-02-09 14:54 UTC, nagdahimanshu approved these changes
LGTM 👍

2022-02-10 17:14 UTC, shuse2 approved these changes

2022-02-10 18:04 UTC, merged