Implement Reclaim command for Legacy module - Closes #588
LiskHQ/lisk-core pull request #600
Opened 2022-02-21 16:43 UTC by nagdahimanshu

### What was the problem?

This PR resolves #588 

### How was it solved?
TODO

### How was it tested?
TODO

2022-02-22 09:53 UTC, ManuGowda commented on src/application/modules/legacy/commands/reclaim.ts
> +			{ chainID: CHAIN_ID, localID: LOCAL_ID },
you need to access this after initialising.
1. in legacy module you should init like this https://github.com/LiskHQ/lisk-sdk/blob/3b5c7507f07c97754efd048c45c3b64ca4ddb99c/framework/src/modules/dpos_v2/module.ts#L135
2. in command u should like this https://github.com/LiskHQ/lisk-sdk/blob/3b5c7507f07c97754efd048c45c3b64ca4ddb99c/framework/src/modules/dpos_v2/commands/pom.ts#L59
3. then access like https://github.com/LiskHQ/lisk-sdk/blob/3b5c7507f07c97754efd048c45c3b64ca4ddb99c/framework/src/modules/dpos_v2/commands/pom.ts#L192


if you need help maybe check with one of SDK team members, to better understand the reasoning. 🙏🏼

2022-02-22 09:54 UTC, ManuGowda requested changes
@nagdahimanshu the code needs to be changed, please check with me or sdk team members for help

2022-02-22 21:51 UTC, ManuGowda commented on package-lock.json
> +		"@ampproject/remapping": {
why is the package-lock changed 🤔 ?

2022-02-22 21:51 UTC, ManuGowda requested changes
code change LGTM, good job @nagdahimanshu 👍🏼

2022-02-23 07:50 UTC, nagdahimanshu commented on package-lock.json
> +		"@ampproject/remapping": {
@ManuGowda I think this change was not expected. I will push the change.

2022-02-24 09:40 UTC, ManuGowda approved these changes

2022-02-24 09:48 UTC, sameersubudhi approved these changes
LGTM overall 👍 
Kindly consider the minor remarks below.

2022-02-24 09:48 UTC, sameersubudhi commented on src/application/modules/legacy/commands/reclaim.ts
> +	Buffer.from(getLegacyAddressFromPublicKey(puhlicKey), 'hex');
```suggestion
const getLegacyAddress = (publicKey): Buffer =>
	Buffer.from(getLegacyAddressFromPublicKey(publicKey), 'hex');
```

2022-02-24 09:48 UTC, sameersubudhi commented on src/application/modules/legacy/commands/reclaim.ts
> +	Buffer.from(getLegacyAddressFromPublicKey(puhlicKey), 'hex');
Please fix the typos.

2022-02-24 09:48 UTC, sameersubudhi commented on src/application/modules/legacy/types.ts
> +export interface ReclaimParamData {
Let us keep the naming consistent throughout.

```suggestion
export interface ReclaimParamsData {
```

2022-02-25 07:34 UTC, merged