Update register BLS key command implementation - Closes #628
LiskHQ/lisk-core pull request #630
Opened 2022-05-23 11:14 UTC by nagdahimanshu

### What was the problem?

This PR resolves #628 

### How was it solved?
TODO

### How was it tested?
TODO

2022-05-31 10:08 UTC, ManuGowda requested changes

2022-05-31 10:08 UTC, ManuGowda commented on src/application/modules/legacy/commands/register_bls_key.ts
> +		const validatorAddress = getAddressFromPublicKey(ctx.transaction.senderPublicKey);
maybe move both validatorAddress and validatorAccount after validator.validate check? if validator.validate check fails then the allocation is not required?

2022-06-02 11:52 UTC, ManuGowda commented on src/application/modules/legacy/schemas.ts
>  export const registerBLSKeyParamsSchema = {
since we changed everything from BLS to keys in general, shall we change everywhere the same (where required)?

2022-06-02 12:16 UTC, ManuGowda approved these changes

2022-06-02 12:37 UTC, sameersubudhi commented on src/application/modules/legacy/commands/register_keys.ts
> +		);
The implementation currently is missing null checks for `generatorKey`, `proofOfPossession` and `blsKey` within the params object.

2022-06-02 12:45 UTC, sameersubudhi commented on test/application/modules/legacy/commands/register_keys.spec.ts
> +		it(`should throw error when validator already has a registered BLS keys`, async () => {
```suggestion
		it('should throw error when validator already has a registered BLS keys', async () => {
```

2022-06-02 12:50 UTC, sameersubudhi commented on test/application/modules/legacy/commands/register_keys.spec.ts
> +			);
Please consider restructuring the it to following. Please remove `await` if it is unnecessary.
```suggestion
		expect(registerBLSKeyCommand.verify(commandVerifyContextInput))
			.resolves.toHaveProperty('status', VerifyStatus.OK);
```

2022-06-02 12:50 UTC, sameersubudhi commented on test/application/modules/legacy/commands/register_keys.spec.ts
> +			);
Same as above.

2022-06-02 12:50 UTC, sameersubudhi commented on test/application/modules/legacy/commands/register_keys.spec.ts
> +			);
Same as above.

2022-06-02 15:02 UTC, MaximeGagnebin requested changes
Looks really good, just left 2 comments.

2022-06-02 15:02 UTC, MaximeGagnebin commented on src/application/modules/legacy/schemas.ts
>  	properties: {
In this params, the length of all properties is fixed.
blsKey must be of length 48 bytes,
proofOfPossession must be of length 96 bytes
generatorKey must be of length 32 bytes.

I don't know if we can add the check directly in the schema (and so it's checked when we do schema validation), or otherwise, we could add these checks to the verification function.

2022-06-02 15:50 UTC, nagdahimanshu commented on test/application/modules/legacy/commands/register_keys.spec.ts
> +			);
Restructuring is not working because `npm run format`  updates the code back to:
```
	await expect(registerBLSKeyCommand.verify(commandVerifyContextInput)).resolves.toHaveProperty(
		     'status',
		     VerifyStatus.OK,
	 ); 
```
Also, removing await leads to lint fail.

2022-06-02 18:57 UTC, sameersubudhi commented on src/application/modules/legacy/commands/register_keys.ts
> +				error: new Error('Validator has a no BLS key.'),
```suggestion
				error: new Error('Validator has no BLS key.'),
```

2022-06-02 19:25 UTC, sameersubudhi approved these changes
LGTM 👍

2022-06-03 11:56 UTC, MaximeGagnebin approved these changes
LGTM! nice work :)

2022-06-03 12:01 UTC, merged