Fix breaking changes from Lisk SDK v6.0.0-alpha.32139 - Closes #659
LiskHQ/lisk-core pull request #660
Opened 2022-08-30 21:08 UTC by nagdahimanshu

### What was the problem?

This PR resolves #659 

### How was it solved?

- [ ] Updating Lisk Core to use SDK canary 6.0.0-alpha.32139
- [ ] Refactor/fix all braking changes
- [ ] Update genesis block and config.json
- [ ] Update unit tests

### How was it tested?
- npm install --registry https://npm.lisk.com/
- npm run build
- ./bin/run start -n devnet

2022-08-31 10:06 UTC, ManuGowda reviewed
Looks fine, please remove the unused code and ID related changes

2022-08-31 14:16 UTC, sameersubudhi commented on config/alphanet/config.json
>  		"modules": {}
Can we please update the config to include the reward milestones?

2022-08-31 14:39 UTC, sameersubudhi commented on src/application/modules/legacy/module.ts
>  	public id = MODULE_ID_LEGACY_BUFFER;
Should we also not remove `id` here and its reference inside the `metadata`?

2022-08-31 14:52 UTC, sameersubudhi commented on src/application/modules/legacy/module.ts
> +		const store = this.stores.get(LegacyAccountStore);
Can we please rename it to `legacyStore` instead and move the declaration to the bottom before it is used?

2022-08-31 15:24 UTC, nagdahimanshu commented on src/application/modules/legacy/module.ts
>  	public id = MODULE_ID_LEGACY_BUFFER;
Removed all references of `id`

2022-08-31 15:47 UTC, sameersubudhi requested changes

2022-08-31 15:47 UTC, sameersubudhi commented on config/alphanet/config.json
> +				"brackets": ["1000000000000", "400000000", "300000000", "200000000", "100000000"]
```suggestion
				"brackets": ["500000000", "400000000", "300000000", "200000000", "100000000"]
```

2022-08-31 15:47 UTC, sameersubudhi commented on config/devnet/config.json
> +				"brackets": ["1000000000000", "400000000", "300000000", "200000000", "100000000"]
```suggestion
				"brackets": ["500000000", "400000000", "300000000", "200000000", "100000000"]
```

2022-08-31 15:47 UTC, sameersubudhi commented on config/alphanet/config.json
> +				"offset": 10,
Let us keep the `offset` similar to the current version. But let it remain `10` for `devnet`.
```suggestion
				"offset": 2160,
```

2022-08-31 16:15 UTC, sameersubudhi approved these changes
Thank you for the changes 🙏

2022-09-01 08:47 UTC, ManuGowda approved these changes

2022-09-01 08:47 UTC, merged