Update legacy module implementation - Closes #658
LiskHQ/lisk-core pull request #661
Opened 2022-09-01 16:04 UTC by nagdahimanshu

### What was the problem?

This PR resolves #658 

### How was it solved?

- [ ] Fix token API init
- [ ] Add schema for KeyRegistrationFailed and ReclaimFailed
- [ ] Add implementation to emit events in case command failure
- [ ] Update verification and execution logic:
  - [ ] Reclaim command
  - [ ] Register BLS key command
- [ ] Update legacy module endpoint implementation

### How was it tested?
- npm install --registry https://npm.lisk.com/
- npm run build
- ./bin/run start -n devnet

2022-09-05 09:52 UTC, ManuGowda commented on src/application/modules/legacy/constants.ts
> +export const TOKEN_ID_LSK = '0000000000000000';
this constant is not exposed from token module? if its accessible from token module we can reuse?

2022-09-05 09:52 UTC, ManuGowda commented on src/application/modules/legacy/constants.ts
> +export const NUM_BYTES_ADDRESS = 20;
same here, if some constants are exposed and reusable, lets reuse 🙏🏼

2022-09-05 09:52 UTC, ManuGowda commented on src/application/modules/legacy/endpoint.ts
> +			const isLegacyAddressExists = await legacyStore.has(ctx, publicKey);
isLegacyAddressExists naming has redundancy as i understand, it can be either

`legacyAddressExists, hasLegacyAddress`, what do you think?

2022-09-06 16:15 UTC, priojeetpriyom approved these changes

2022-09-09 09:57 UTC, sameersubudhi requested changes

2022-09-09 09:57 UTC, sameersubudhi commented on test/application/modules/legacy/commands/register_keys.spec.ts
> +			expect(registerKeysCommand.name).toBe(COMMAND_REGISTER_KEYS);
Please update the test case description from `should throw error when validator has a no BLS keys` to `should throw an error when a validator has no BLS key`

2022-09-09 09:57 UTC, sameersubudhi commented on src/application/modules/legacy/constants.ts
> +export const TOKEN_ID_LSK = '0000000000000000';
In the [PR](https://github.com/LiskHQ/lips/pull/169/files) (L53 of `proposals/lip-0050.md`) states `TOKEN_ID_LSK` to be `0x0000000000000000`. Why do we use a string instead of a hex value?

2022-09-12 09:54 UTC, nagdahimanshu commented on src/application/modules/legacy/constants.ts
> +export const TOKEN_ID_LSK = '0000000000000000';
Clarified offline!

2022-09-12 20:49 UTC, sameersubudhi approved these changes
Apart from the highlighted error message, everything else seems good 👍

2022-09-12 20:49 UTC, sameersubudhi commented on src/application/modules/legacy/commands/reclaim.ts
> -	public typeID = TYPE_ID_ACCOUNT_RECLAIM;
The error message `Legacy address corresponding to sender publickey ${senderPublicKey} was not found` does not match the error message defined in the LIP. Please update the same.

2022-09-13 07:02 UTC, ManuGowda approved these changes

2022-09-13 07:02 UTC, merged