No version number in PM2 - Closes #538
LiskHQ/lisk-core pull request #662
Opened 2022-09-05 11:44 UTC by priojeetpriyom

### What was the problem?

This PR resolves #538

### How was it solved?

### How was it tested?

2022-09-05 13:11 UTC, ManuGowda approved these changes

2022-09-05 13:11 UTC, ManuGowda commented on ecosystem.config.js
> + * LiskHQ/lisk-service
```suggestion
```

2022-09-05 13:56 UTC, sameersubudhi requested changes

2022-09-05 13:56 UTC, sameersubudhi commented on ecosystem.config.js
> +			log_date_format: 'YYYY-MM-DD HH:mm:ss SSS',
Logging time granularity up to seconds should be fine.
```suggestion
			log_date_format: 'YYYY-MM-DD HH:mm:ss,
```

2022-09-05 13:56 UTC, sameersubudhi commented on ecosystem.config.js
> +			ref: 'origin/release/4.0.0',
The `ref` should be set to the `main` branch by default.
```suggestion
			ref: 'origin/main',
```

2022-09-05 13:56 UTC, sameersubudhi commented on ecosystem.config.js
> +			ref: 'origin/release/4.0.0',
Same as above.
```suggestion
			ref: 'origin/main',
```

2022-09-05 13:56 UTC, sameersubudhi commented on ecosystem.config.js
> +			'post-deploy': 'source ~/.bashrc && source ~/.zshrc && pm2 start ecosystem.config.js',
Please verify what happens when either of `~/.bashrc` or `~/.zshrc` doesn't exist and handle the situation accordingly.

2022-09-05 13:56 UTC, sameersubudhi commented on ecosystem.config.js
> +			'post-deploy': 'source ~/.bashrc && pm2 start ecosystem.config.js',
Same as above.

2022-09-05 14:23 UTC, priojeetpriyom commented on ecosystem.config.js
> +			'post-deploy': 'source ~/.bashrc && pm2 start ecosystem.config.js',
Applied

2022-09-05 14:24 UTC, priojeetpriyom commented on ecosystem.config.js
> +			'post-deploy': 'source ~/.bashrc && source ~/.zshrc && pm2 start ecosystem.config.js',
Applied. It did not execute following commands, fixed this buy pipelining with a fallback true condition. Thanks for the suggestion 👍

2022-09-05 14:24 UTC, priojeetpriyom commented on ecosystem.config.js
> +			ref: 'origin/release/4.0.0',
Applied

2022-09-05 14:24 UTC, priojeetpriyom commented on ecosystem.config.js
> +			ref: 'origin/release/4.0.0',
Applied.

2022-09-05 15:14 UTC, priojeetpriyom commented on ecosystem.config.js
> +			'post-deploy': 'source ~/.bashrc || true && pm2 start ecosystem.config.js',
checking

2022-09-05 15:18 UTC, nagdahimanshu commented on ecosystem.config.js
> +				LISK_NETWORK: 'mainnet',
I would also recommend to add all the supported environment variables with thier default values
```suggestion
				LISK_NETWORK: 'mainnet',
				LISK_API_IPC: true,
				LISK_ENABLE_FORGER_PLUGIN: true,
				LISK_API_WS: true,
				LISK_API_WS_PORT: 7887,
				LISK_CONSOLE_LOG_LEVEL:  'warn',				
```

2022-09-06 08:10 UTC, priojeetpriyom commented on ecosystem.config.js
> +			'post-deploy': 'source ~/.bashrc || true && pm2 start ecosystem.config.js',
Applied

2022-09-06 08:10 UTC, priojeetpriyom commented on ecosystem.config.js
> +				LISK_NETWORK: 'mainnet',
Applied

2022-09-07 13:27 UTC, nagdahimanshu approved these changes
Looks good to me 👍

2022-09-09 15:57 UTC, sameersubudhi approved these changes
Thank you for the contribution @priojeetpriyom!! 🙏

2022-09-09 15:59 UTC, merged