Create script to generate transactions - Closes #676
LiskHQ/lisk-core pull request #682
Opened 2022-10-26 14:23 UTC by nagdahimanshu

### What was the problem?

This PR resolves #676 

### How was it solved?

TODO
### How was it tested?

Local

2022-10-30 09:48 UTC, sameersubudhi commented on test/scripts/utils/constants.ts
> +export const COMMAND_AUTH_REGISTER_MULTISIGNATURE = 'registerMultisignature';
```suggestion
export const MODULE_TOKEN = 'token';
export const COMMAND_TOKEN_TRANSFER = 'transfer';

export const MODULE_DPOS = 'dpos';
export const COMMAND_DPOS_REGISTER_DELEGATE = 'registerDelegate';
export const COMMAND_DPOS_VOTE_DELEGATE = 'voteDelegate';
export const COMMAND_DPOS_UPDATE_GENERATOR_KEY = 'updateGeneratorKey';

export const MODULE_AUTH = 'auth';
export const COMMAND_AUTH_REGISTER_MULTISIGNATURE = 'registerMultisignature';
```

2022-10-31 11:14 UTC, sameersubudhi requested changes

2022-10-31 11:14 UTC, sameersubudhi commented on test/scripts/utils/constants.ts
> +export const MESSAGE_TAG_MULTISIG_REG = 'LSK_RMSG_';
```suggestion
export const TAG_MULTISIG_REG = 'LSK_RMSG_';
```

2022-10-31 11:14 UTC, sameersubudhi commented on test/scripts/utils/multisignature.ts
> +		Buffer.from('04000000', 'hex'),
Can we please fetch and assign the `chainID` dynamically from the `getNodeInfo` endpoint instead?

2022-10-31 11:14 UTC, sameersubudhi commented on test/scripts/utils/multisignature.ts
> +		Buffer.from('04000000', 'hex'),
Same as above.

2022-10-31 11:14 UTC, sameersubudhi commented on test/scripts/utils/multisignature.ts
> +export const getParamsBytes = params => codec.encode(multisigRegParams, params);
```suggestion
export const getParamsBytes = (paramsSchema, params) => codec.encode(paramsSchema, params);
```

2022-10-31 11:14 UTC, sameersubudhi commented on test/scripts/utils/multisignature.ts
> +	const paramsBytes = getParamsBytes({
```suggestion
	const paramsBytes = getParamsBytes(multisigRegParams, {
```

2022-10-31 11:14 UTC, sameersubudhi commented on test/scripts/utils/schemas.ts
> +export const baseTransactionSchema = {
All these schemas should be available from the node. If available, kindly cache them and reuse. Please create an issue with the SDK if these schemas are not available from the node.

2022-10-31 15:52 UTC, priojeetpriyom commented on test/scripts/utils/transactions/create.ts
> +	);
Could it be a loop instead?

2022-10-31 15:52 UTC, priojeetpriyom commented on test/scripts/utils/transactions/send.ts
> +	return Number(account.nonce);
Shouldn't we convert it to BigInt?

2022-11-01 14:02 UTC, priojeetpriyom approved these changes

2022-11-02 00:59 UTC, sameersubudhi commented on test/scripts/utils/transactions/create.ts
> +		tokenID: TOKEN_ID,
Can we please make the `TOKEN_ID` dynamic based on the `chainID` from the node info? This might break after we upgrade to SDK v6.0.0-alpha.5.

2022-11-03 00:06 UTC, sameersubudhi requested changes
Could you please also set the `mainchain` flag in `https://github.com/LiskHQ/lisk-core/blob/a699501d12fa2d856610e2c3890163859bb354c7/src/application/index.ts#L19`?

Currently the application is initialized as a sidechain.

Also, import `ModuleMetadata` type from the `lisk-sdk` in `src/application/modules/legacy/module.ts`.

```
import {
	BaseModule,
	TokenMethod,
	ModuleMetadata,
	ValidatorsMethod,
	GenesisBlockExecuteContext,

	codec,
	utils,
	validator as liskValidator,
} from 'lisk-sdk';
```

2022-11-10 15:29 UTC, sameersubudhi approved these changes
LGTM 👍

2022-11-11 10:51 UTC, merged