:sparkles: Add chain connector plugin
LiskHQ/lisk-core pull request #737
Opened 2023-02-24 14:17 UTC by ManuGowda

### What was the problem?

This PR resolves #INSERT_ISSUE_NUMBER

### How was it solved?

### How was it tested?

2023-02-27 09:15 UTC, sameersubudhi requested changes
Code changes look good. Could you please confirm if the alphanet/devnet genesis blocks were recreated post the change made in `src/application/modules/legacy/module.ts`? If I run through the following steps locally a different genesis block gets generated for both the networks.

- `nvm use`
- `npm ci`
- `npm run build`
- `./bin/run genesis-block create -n devnet -o ./config/devnet -f ./config/devnet/genesis_assets.json`
- `./bin/run genesis-block create -n alphanet -o ./config/alphanet -f ./config/alphanet/genesis_assets.json`

2023-02-27 09:15 UTC, sameersubudhi commented on src/application/modules/legacy/module.ts
>  		this.events.register(ReclaimLSKEvent, new ReclaimLSKEvent(this.name));
Could we please add an empty line for visual clarity in separation of store and event registration.
```suggestion
		this.stores.register(LegacyAccountStore, new LegacyAccountStore(this.name, 0));

		this.events.register(ReclaimLSKEvent, new ReclaimLSKEvent(this.name));
```

2023-02-27 09:19 UTC, sameersubudhi commented on src/application/modules/legacy/module.ts
>  		this.events.register(ReclaimLSKEvent, new ReclaimLSKEvent(this.name));
Also, seeing the following error when running the node with the chain connector enabled:

Start command:
```
./bin/run start -n devnet --api-ipc -l debug --api-ws --enable-chain-connector-plugin
```

Logged error:
```
2023-02-27T09:16:56.764Z DEBUG Sameers-MacBook-Pro.local plugin_chainConnector 27584 [plugin=chainConnector] Plugin is registered to bus
2023-02-27T09:16:56.767Z ERROR Sameers-MacBook-Pro.local plugin_chainConnector 27584 [err=Lisk validator found 3 error[s]:
Missing property, must have required property 'ccuFee'
Missing property, must have required property 'encryptedPrivateKey'
Missing property, must have required property 'password'] Fail to handle message.
```

2023-02-27 12:05 UTC, ManuGowda commented on src/application/modules/legacy/module.ts
>  		this.events.register(ReclaimLSKEvent, new ReclaimLSKEvent(this.name));
I think all of these are optional config params? @shuse2 is this correct?

2023-02-28 09:52 UTC, sameersubudhi approved these changes
LGTM 👍

2023-02-28 10:17 UTC, nagdahimanshu approved these changes
Looks good 👍

2023-02-28 10:21 UTC, merged