Update application config and genesis block for devnet and alphanet
LiskHQ/lisk-core pull request #750
Opened 2023-03-28 11:12 UTC by nagdahimanshu

### What was the problem?

This PR resolves #749 

### How was it solved?

- [x] Update the devnet and alphanet genesis config with:
  - [x] Reduced distance for default rewards
- [x] Update the devnet and alphanet genesis assets with:
  - [x] Self stakes for all the init-validators
  - [x] Pending unlocks for stakers
  - [x] Set commission to 50% (5000) for all the validators
- [x] Regenerate the devnet and alphanet genesis blocks with the above changes
- [x] Generate genesis block for betanet (without the above changes, as per existing configuration)
- [x] Update configurations for all networks

### How was it tested?

- ./bin/run start -n devnet  --api-ws --api-ipc -l info
-  npm run test:stress

2023-03-28 12:01 UTC, sameersubudhi requested changes

2023-03-28 14:38 UTC, sameersubudhi requested changes
Also, please ensure that the total supply and total locked in the token module is also updated.
For calculation of the `sharingCoefficients` please refer to https://github.com/LiskHQ/lips/blob/main/proposals/lip-0070.md#efficient-calculation-of-rewards.

2023-03-28 14:38 UTC, sameersubudhi commented on config/devnet/genesis_assets.json
> +								"sharingCoefficients": []
Same here.

2023-03-28 14:38 UTC, sameersubudhi commented on config/devnet/genesis_assets.json
> +								"amount": "100000000",
`amount` must be at least `1000 LSK (viz. 100000000000)` and in multiples of 10 LSK (must end with atleast 9 zeros and greater than 100000000000).

2023-03-28 16:56 UTC, ManuGowda approved these changes

2023-03-28 21:05 UTC, sameersubudhi commented
When running Lisk Core with `devnet` config, I notice that `consecutiveMissedBlocks` is always non-zero (either 16 or 17) and the `sharingCoefficients[0].coefficient` is empty for all the validators. 

`sharingCoefficients[0].coefficient` is empty for alphanet as well. (To run alphanet, I'd to regenerate the genesis block with `modules.pos.useInvalidBLSKey: false` to bypass the current bug in SDK). However, `consecutiveMissedBlocks` was zero as expected.

Could you please confirm with the SDK/Research team if we need to fix anything at our end?

Eg (devnet):
```
    {
      "name": "genesis_43",
      "totalStake": "100000000000",
      "selfStake": "100000000000",
      "lastGeneratedHeight": 0,
      "isBanned": false,
      "reportMisbehaviorHeights": [],
      "consecutiveMissedBlocks": 16,
      "commission": 5000,
      "lastCommissionIncreaseHeight": 0,
      "sharingCoefficients": [
        {
          "tokenID": "0400000000000000",
          "coefficient": ""
        }
      ],
      "address": "lskg2ktfe4n4yd963pusqf8vbgqv7arwx9c5o8kpu",
      "punishmentPeriods": []
    }
```

2023-03-29 14:30 UTC, sameersubudhi approved these changes
Thank you for all the changes @nagdahimanshu. LGTM 👍

2023-03-29 14:36 UTC, ManuGowda approved these changes

2023-03-29 22:36 UTC, merged