Rename node command to system
LiskHQ/lisk-core pull request #763
Opened 2023-04-13 12:21 UTC by priojeetpriyom

### What was the problem?

This PR resolves #761

### How was it solved?

- [x] Rename node command to system

### How was it tested?

- [x] Local

2023-04-13 13:20 UTC, vardan10 commented on docs/commands/system.md
> +_See code: [dist/commands/node/metadata.ts](https://github.com/LiskHQ/lisk-core/blob/v4.0.0-alpha.14/dist/commands/system/metadata.ts)_
```suggestion
_See code: [dist/commands/system/metadata.ts](https://github.com/LiskHQ/lisk-core/blob/v4.0.0-alpha.14/dist/commands/system/metadata.ts)_
```

2023-04-13 13:21 UTC, vardan10 commented on docs/commands/system.md
> +_See code: [dist/commands/node/info.ts](https://github.com/LiskHQ/lisk-core/blob/v4.0.0-alpha.14/dist/commands/system/node-info.ts)_
```suggestion
_See code: [dist/commands/system/info.ts](https://github.com/LiskHQ/lisk-core/blob/v4.0.0-alpha.14/dist/commands/system/node-info.ts)_
```

2023-04-13 13:32 UTC, vardan10 commented
We also need to change readme 
https://github.com/LiskHQ/lisk-core/blob/761-rename-node-command-to-system/README.md?plain=1#L87
https://github.com/LiskHQ/lisk-core/blob/761-rename-node-command-to-system/README.md?plain=1#L209

2023-04-13 14:27 UTC, priojeetpriyom commented on docs/commands/system.md
> +_See code: [dist/commands/node/info.ts](https://github.com/LiskHQ/lisk-core/blob/v4.0.0-alpha.14/dist/commands/system/node-info.ts)_
Applied.

2023-04-13 15:15 UTC, vardan10 approved these changes

2023-04-14 06:48 UTC, nagdahimanshu commented on docs/commands/system.md
> +* [`lisk-core system:metadata`](#lisk-core-nodemetadata)
```suggestion
* [`lisk-core system:node-info`](#lisk-core-systemnode-info)
* [`lisk-core system:metadata`](#lisk-core-systemmetadata)
```

2023-04-14 09:27 UTC, nagdahimanshu approved these changes

2023-04-14 13:41 UTC, ManuGowda commented on docs/commands/system.md
> +  $ lisk-core system:info
@priojeetpriyom shouldn't this be `src/commands/system/node-info.ts` `system:node-info`?

2023-04-14 13:42 UTC, ManuGowda requested changes
minor change

2023-04-15 09:17 UTC, priojeetpriyom commented on docs/commands/system.md
> +  $ lisk-core system:info
Applied.

2023-04-17 09:37 UTC, merged