:arrow_up: Bump version
LiskHQ/lisk-core pull request #768
Opened 2023-04-21 09:03 UTC by ManuGowda

### What was the problem?

This PR resolves #INSERT_ISSUE_NUMBER

### How was it solved?

### How was it tested?

2023-04-21 09:24 UTC, sameersubudhi requested changes
We need to add few more accounts to the `genesis_assets.json`. @nagdahimanshu can assist you with it.

Also, please consider updating the config/genesis block/dependencies for devnet and alphanet as well. If we do not intend to use it anymore, then maybe entirely remove them.

2023-04-21 09:24 UTC, sameersubudhi commented on config/betanet/config.json
>  	},
Optional: The entire `generator` property can probably be removed.

2023-04-21 09:39 UTC, ManuGowda commented on config/betanet/config.json
>  	},
@ishantiw and @shuse2 suggested to keep it, I tested the app and its working fine with this config. Let me know what you guys think.

2023-04-21 09:40 UTC, shuse2 commented on config/betanet/config.json
>  	},
if it works, either ways are fine

2023-04-21 09:44 UTC, sameersubudhi commented on config/betanet/config.json
>  	},
It should work as is, hence the optional recommendation. 🙂

2023-04-21 11:43 UTC, sameersubudhi approved these changes
LGTM 👍

2023-04-21 13:50 UTC, nagdahimanshu commented
@ManuGowda, @sameersubudhi `keepEventsForHeights` in `betanet` config is set to 300. Do we have to change it to -1?

2023-04-24 13:35 UTC, shuse2 approved these changes

2023-04-24 16:58 UTC, sameersubudhi approved these changes

2023-04-24 17:01 UTC, merged