Test docker set up page
LiskHQ/lisk-core pull request #779
Opened 2023-05-23 10:20 UTC by chris529

When Lisk core v4 image is ready and the beta version is available, then test the Docker set up with lisk-core v4.

lisk-docs/lisk-core/v4/setup/docker.html

(This issue pertains to the already merged PR Update Docker setup page: https://github.com/LiskHQ/lisk-docs/pull/1642)

Closes #1605 in docs-core

2023-05-23 10:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LiskHQ/lisk-core?pullRequest=779) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LiskHQ/lisk-core?pullRequest=779) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LiskHQ/lisk-core?pullRequest=779) it.</sub>

2023-05-23 21:43 UTC, sameersubudhi requested changes

2023-05-23 21:43 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +It is also possible to use {url_podman}[podman] instead of docker by simply replacing the occurrences of docker with `podman`, in the following examples or alternatively by creating an alias with the
This is a command, hence it must be as below:
```suggestion
It is also possible to use {url_podman}[podman] instead of docker by simply replacing the occurrences of docker with `podman`, in the following examples or alternatively by creating an alias with `alias docker=podman`.
```

2023-05-23 21:43 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
Additionally, could you please re-verify that the contents are exactly as in https://github.com/LiskHQ/lisk-core/blob/development/docker/README.md.

2023-05-24 12:39 UTC, sameersubudhi approved these changes
LGTM 👍

2023-05-24 16:12 UTC, priojeetpriyom approved these changes

2023-05-25 12:42 UTC, merged