Update migration guide v3-> v4
LiskHQ/lisk-core pull request #794
Opened 2023-06-16 11:44 UTC by Tschakki

### What was the problem?

This PR resolves #785 

### How was it tested?

https://liskhq.github.io/lisk-docs/lisk-core/v4/management/migration.html

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +=== Enabling block generation after migration (for validators)
```suggestion
=== Enabling block generation after the migration (for validators)
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +==== Download checksum and verify
```suggestion
==== Download the checksum and verify
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Download the checksum and verify the successful download of lisk-migrator.
```suggestion
Download the checksum and verify the successful download of the lisk-migrator.
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +In case `lisk-migrator` was extracted somewhere else other than in your home directory, replace `$HOME` with the absolute path of where the `lisk-migrator` folder is located.
```suggestion
In case the `lisk-migrator` was extracted somewhere else other than in your home directory, replace `$HOME` with the absolute path of where the `lisk-migrator` folder is located.
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +The height is needed by `lisk-migrator` in the next step.
```suggestion
The height is needed by the `lisk-migrator` in the next step.
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +If you have added `lisk-migrator` to the PATH as described in the section <<setting-up-the-lisk-migrator>>, you can start the migration script by running the following command footnote:snap_footnote[
```suggestion
If you have added the `lisk-migrator` to the PATH as described in the section <<setting-up-the-lisk-migrator>>, you can start the migration script by running the following command footnote:snap_footnote[Snap versions of Lisk Core store everything in `~/snap/lisk-core/current/.lisk/lisk-core` instead of `~/.lisk/lisk-core`] in the terminal:
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Shortly before the migration occurs, it is possible to reattach to it in order to check if everything is working correctly.
```suggestion
Shortly before the migration occurs, it is possible to reattach the screen to it in order to check if everything is working correctly.
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +First check the name of the detached screen:
```suggestion
First, check the name of the detached screen:
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Observe if `lisk-migrator` finishes successfully, (this can take several minutes).
```suggestion
Observe if the `lisk-migrator` finishes successfully, (this can take several minutes).
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +The flag `--auto-migrate-config` will automatically migrate the config from old to new node.
```suggestion
The flag `--auto-migrate-config` will automatically migrate the config from the old to the new node.
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +After the snapshot height is reached, validators have approximately 2 hours time to enable block generation, to ensure they will not miss any blocks after the hardfork.
```suggestion
After the snapshot height is reached, validators have approximately 2 hours time to enable block generation, to ensure they will not miss any blocks after the hard fork.
```

2023-06-20 09:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +`initRounds` is number of rounds for the bootstrap period of the new network.
```suggestion
`initRounds` is the number of rounds for the bootstrap period of the new network.
```

2023-06-20 15:17 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +For more information check the {url_lisk_blog_migration}[Testnet migration announcement^].
yes, this needs to be updated once the articles are out. I can comment it out for now

2023-06-20 15:18 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Replace the address with your delegate address in hexadecimal representation.
```suggestion
Replace the address with your validator address.
```

2023-06-20 15:37 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Shortly before the migration occurs, it is possible to reattach to it in order to check if everything is working correctly.
```suggestion
Shortly before the migration occurs, it is possible to reattach to the screen, in order to check if everything is working correctly.
```

2023-06-21 11:27 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +:initRounds: TBD
Done: https://github.com/LiskHQ/lisk-core/issues/795

2023-06-23 10:08 UTC, ManuGowda reviewed
@Tschakki In general LGTM, I have left minor comments.

I know if its too late, but migration guide/process seems to be lengthy due its nature of steps. 

What I can recommend is you can convert all these steps into a Makefile with the help of devops? and allow params to be passed in so that we can pass `height, network` etc.. to make it generic for testnet and mainnet?

This can make job of migration easy and smooth process.

2023-06-23 10:08 UTC, ManuGowda commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +After the snapshot height is reached, validators have approximately 2 hours time to enable block generation, to ensure they will not miss any blocks after the hard fork.
I think this timeline of 2hrs is not measured? maybe we can put this stats based on testnet/mainnet migration testing?

2023-06-23 10:08 UTC, ManuGowda commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +==== Enable block generation
cant we link to the sections in docs https://lisk.com/documentation/lisk-core/v4/core-cli.html#generatorenable?

2023-06-23 10:08 UTC, ManuGowda commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +==== Set the hash onion
same here, where possible we can link the existing docs? or it was by choice that we have it separate?

2023-06-23 13:34 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Check the current block height of your node directly in the terminal by running the following command:
This is covered in the preparation steps :)

2023-06-26 09:31 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +:url_lisk_blog_migration: https://lisk.com/blog/development/announcing-lisk-testnet-v3-migration
It are links to the old migration posts, they are commented out in the content, and will be updated and uncommented, once the new blog posts are published :)

2023-06-26 09:33 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +//TODO: Update steps
resolved it 👍

2023-06-26 10:00 UTC, Nazgolze commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +:lisk-migrator: lisk-migrator-v2.0.0-linux-x64.tar.gz
I think linux-x64, darwin-x64 and darwin-arm64

2023-06-26 10:29 UTC, Nazgolze requested changes

2023-06-26 10:29 UTC, Nazgolze commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> + @reboot /bin/bash /home/lisk/lisk-test/lisk.sh start > /home/lisk/lisk-test/cron.log 2>&1
This is old, from the lisk 2.x and older days, and should be removed.

Users that have set something up to start lisk-core on boot, whether it's through cron or systemd or something else, should keep that in mind and adjust things accordingly so that lisk-core 4.x gets started instead of lisk-core 3.x

2023-06-26 10:29 UTC, Nazgolze commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +bash lisk.sh stop
This is old too. Anything referencing `lisk.sh` should be changed or removed

2023-06-26 11:47 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +bash lisk.sh stop
@Nazgolze what is the command for this in the new version?

2023-06-26 11:59 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2023-06-26 11:59 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Alternatively users can also verify the current height by comparing `data.height` in the response from the https://service.lisk.com/api/v2/network/status endpoint.
```suggestion
Alternatively, users can also verify the current height by comparing `data.height` in the response from the https://service.lisk.com/api/v2/network/status endpoint.
```

2023-06-26 11:59 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +To directly check the current height via command line, run:
```suggestion
To directly check the current height via the command line, run:
```

2023-06-26 15:04 UTC, ManuGowda approved these changes

2023-06-27 11:35 UTC, Nazgolze approved these changes

2023-06-27 11:44 UTC, sameersubudhi requested changes

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +:initRoundsTime: TBD hours
`initRounds` will be `60480`. So, `initRoundsTime` will be approx 1 week.
Ref: `POS_INIT_ROUNDS` in https://github.com/LiskHQ/lips/blob/main/proposals/lip-0063.md#constants.

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Optionally, anyone running a Lisk Core v3.0.5 who is not an active validator can participate in the migration process.
```suggestion
Optionally, anyone running a Lisk Core v3.0.5 who is not an active validator can also participate in the migration process.
```

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +In this case, the following steps 2.7 and 2.8 in this guide can be skipped, as they are only relevant for validators.
```suggestion
In this case, the following steps 2.7 and 2.8 in this guide can be skipped, as they are only relevant for the current validators.
```

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +* minimum of 4 GB RAM
We have a minimum requirement of 4 GB RAM for only Lisk Core. So, to run the migrator we will ideally need more but I do not have numbers around that. Maybe @Nazgolze can suggest a safe number? (6 or 8 GB perhaps).

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +If your version is lower than 3.0.5, ensure to update Lisk Core before proceeding with the migration.
Users should preferrably check the node info response for the version of their running node (`lisk-core node:info --pretty`). If their HTTP API is enabled, they can check `data.version` from `https://mainnet.lisk.com/api/node/info` (reference).
Or, `apiClient.node.getNodeInfo();`

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +sha256sum -c {lisk-migrator}.SHA256
Darwin doesn't offer `sha256sum` like in Linux. Instead, you'll need to use `sha -a 256`.

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +lisk-migrator --snapshot-height {snapshotHeight} --output ~/.lisk/lisk-core/config/mainnet --lisk-core-v3-data-path ~/.lisk/custom/path/ --auto-download-lisk-core-v4  --auto-migrate-config --auto-sta
Maybe we should avoid the `.` in `--lisk-core-v3-data-path ~/lisk/custom/path/`.
```suggestion
lisk-migrator --snapshot-height {snapshotHeight} --output ~/.lisk/lisk-core/config/mainnet --lisk-core-v3-data-path ~/lisk/custom/path/ --auto-download-lisk-core-v4  --auto-migrate-config --auto-start-lisk-core-v4
```

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Observe if the `lisk-migrator` finishes successfully, (this can take several minutes).
It is probably better to give them an estimation. approx, 10 mins against the testnet and 3hrs against the mainnet.

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +For validators, this might result in missing blocks, for everyone else it will not have any impact.
```suggestion
For validators, this might result in missing blocks. For everyone else, it will not have any impact.
```

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Additionally, for blocks to be finalized, enough of the active validators (min. 68) need to participate in the migration process.
Since we do not usually use abbreviations in our documentations.
```suggestion
Additionally, for blocks to be finalized, enough of the active validators (minimum 68) need to participate in the migration process.
```

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Especially the non encrypted values need to be treated *as equally sensitive as the passphrase for an account.*
```suggestion
Especially the non-encrypted values need to be treated *as equally sensitive as the passphrase for an account.*
```

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +IMPORTANT: The registration of the legacy validator keys has to be done *latest at the end of `initRounds`*, to be eligible to generate blocks in the new network.
It's important to highlight/repeat the same information about non-init validators being banned during the migration process.

2023-06-27 11:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Otherwise, the validator will be *banned* in the network, until the validator keys are registered in the legacy module.
```suggestion
Otherwise, the validator will continue to be *banned* on the network, until the validator keys are registered in the legacy module.
```

2023-06-27 11:49 UTC, Nazgolze commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +It will be required every time to enable block generation, in order to decrypt the generator keys in the node.
I would keep `The password is sensitive information` as is and only change 'in' to 'on'

2023-06-27 11:53 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +It will be required every time to enable block generation, in order to decrypt the generator keys in the node.
My bad 🤦 Updated the suggestion.

2023-06-27 11:56 UTC, Nazgolze commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +* minimum of 4 GB RAM
That's a good point.

It's the genesis block that takes up a lot of RAM. I can't really say what a good number is without testing this

2023-06-27 12:59 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +* minimum of 4 GB RAM
Then, we should perhaps leave a TODO so that we can come back and update with the exact recommendation. @Tschakki For now, I'd recommend you to update it to 8GB instead.

2023-06-27 13:06 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +The flag `--auto-download-lisk-core-v4` will also download and install Lisk Core v4 for you.
it wont only download the CLI tool, but whole Lisk Core, or not? So why update it?

2023-06-27 13:09 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +rm -r lisk-core
This is referring to the old `lisk-core` version, which i assume to be present under `lisk-core/`, but maybe it is not clear enough as the folder with new version might have same name. 🤔  Will remove the code snippet, to avoid confusion

2023-06-27 13:15 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +The flag `--auto-download-lisk-core-v4` will also download and install Lisk Core v4 for you.
No, it only downloads the Lisk Core CLI from npm registry. Check [here](https://github.com/LiskHQ/lisk-migrator/blob/00b953da7ee8d16dd80624cad6498a78c496677c/src/utils/node.ts#L31).

2023-06-27 13:48 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +IMPORTANT: The registration of the legacy validator keys has to be done *latest at the end of `initRounds`*, to be eligible to generate blocks in the new network.
Is there anywhere, where you would you like this to be highlighted/repeated specifically?

2023-06-27 13:49 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +IMPORTANT: The registration of the legacy validator keys has to be done *latest at the end of `initRounds`*, to be eligible to generate blocks in the new network.
In the `Register legacy validator keys` section as an important note perhaps!?

2023-06-27 15:02 UTC, sameersubudhi approved these changes
Thank you for the changes. Now, looks good 👍 
However, please consider the following recommendations.

2023-06-27 15:02 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +To be un-banned, a validator needs to <<register-legacy-validator-keys>>.
The users are unaware so far that the migration process marks all the non-init validators `banned`. So, maybe already give them that context here or in the paragraphs before.

2023-06-27 15:04 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +IMPORTANT: As already mentioned, all non-initial validators will be banned during the bootstrap period.
Also, please highlight `banned` here 🙂

2023-06-27 15:07 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +To be un-banned, a validator needs to <<register-legacy-validator-keys>>.
I aded this info in line 392 :)

2023-06-27 15:21 UTC, merged