Update setup guides in core docs to include steps to connect to a local devnet
LiskHQ/lisk-core pull request #814
Opened 2023-07-20 08:58 UTC by chris529

2023-07-25 13:50 UTC, sameersubudhi approved these changes

2023-07-25 13:50 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
> +NOTE: The passphrase for the genesis account can be found here in the Lisk Core GitHub repository under the following path: xref:{url_devnet_passphrase}[config/devnet/passphrase.json].
```suggestion
NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: xref:{url_devnet_passphrase}[config/devnet/passphrase.json].
```

2023-07-25 13:50 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/npm.adoc
> +NOTE: The passphrase for the genesis account can be found here in the Lisk Core GitHub repository under the following path: xref:{url_devnet_passphrase}[config/devnet/passphrase.json].
```suggestion
NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: xref:{url_devnet_passphrase}[config/devnet/passphrase.json].
```

2023-07-26 08:09 UTC, TalhaMaliktz requested changes

2023-07-26 08:09 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +Please refer to {url_docker_install}[https://docs.docker.com/engine/installation].
Please use the variable convention for links

2023-07-26 08:09 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: xref:{url_devnet_passphrase}[config/devnet/passphrase.json].
```suggestion
NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: {url_devnet_passphrase}[config/devnet/passphrase.json].
```

2023-07-26 08:09 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/npm.adoc
> +NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: xref:{url_devnet_passphrase}[config/devnet/passphrase.json].
```suggestion
NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: {url_devnet_passphrase}[config/devnet/passphrase.json].
```

2023-07-26 08:09 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/snap.adoc
> +NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: xref:{url_devnet_passphrase}[config/devnet/passphrase.json].
```suggestion
NOTE: The passphrase for the genesis account(s) can be found here in the Lisk Core GitHub repository under the following path: {url_devnet_passphrase}[config/devnet/passphrase.json].
```

2023-07-27 07:44 UTC, TalhaMaliktz approved these changes
Thank you! LGTM 👍🏼

2023-07-27 09:02 UTC, merged