Hardware requirements for installation in Core docs
LiskHQ/lisk-core pull request #822
Opened 2023-08-03 15:35 UTC by chris529

Closes https://github.com/LiskHQ/lisk-docs/issues/29

2023-08-09 09:18 UTC, Tschakki requested changes

2023-08-09 09:18 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
> +Hence, adhering to the above listed requirements is highly recommended.
This should be added as a footnote.

2023-08-09 10:01 UTC, chris529 commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
> +=== Hardware requirements
Good point, now done 👍

2023-08-10 10:14 UTC, Tschakki requested changes
Looking good already!

2023-08-10 10:14 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
> +NOTE: These recommendations are derived from the log level settings, in the event that the user needs to increase storage to prevent limited memory access and potential memory-related problems with a
Please turn all notes into footnotes

2023-08-10 13:03 UTC, chris529 commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
> +NOTE: These recommendations are derived from the log level settings, in the event that the user needs to increase storage to prevent limited memory access and potential memory-related problems with a
I have now converted all the relevant notes in each setup page into footnotes...That is a good point, as I agree a footnote here is more appropriate. 👍

2023-08-11 09:41 UTC, Tschakki approved these changes
LGTM 👍

2023-08-15 10:36 UTC, nagdahimanshu approved these changes
LGTM 👍

2023-08-15 17:52 UTC, merged