Update migration guide
LiskHQ/lisk-core pull request #847
Opened 2023-09-21 09:29 UTC by Tschakki

### What was the problem?

This PR resolves #795 

### How was it tested?

https://liskhq.github.io/lisk-docs/lisk-core/v4/management/migration.html

2023-09-21 12:30 UTC, sameersubudhi requested changes

2023-09-21 12:30 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Replace the address `lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3` with your validator address, and set the values for `height`, `max-height-generated` and `max-height-prevoted` to the values listed in
We must also specify the correspondence of the properties that the users need to follow:

From forgingStatus.json --> generator:enable command:
- `height` --> `--height`
- `maxHeightPrevoted` --> `--max-height-prevoted`
- `maxHeightPreviouslyForged` --> `--max-height-generated`

```suggestion
Replace the address `lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3` with your validator address, and set the values for `height`, `max-height-generated` and `max-height-prevoted` to the values listed in the `forgingStatus.json` file corresponding your address.
```

2023-09-21 12:30 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +. In step <<wait-until-the-network-reaches-the-snapshot-height>>, invoke the xref:{url_api_forgingstatus}[app:getForgingStatus] endpoint on the remote Lisk Core v3 node, as soon as the snapshot heigh
```suggestion
. In step <<wait-until-the-network-reaches-the-snapshot-height>>, invoke the xref:{url_api_forgingstatus}[app:getForgingStatus] endpoint on the remote Lisk Core v3 node, as soon as the snapshot height is reached, and note down the returned values. We recommend automating it with a script to ensure precision.
```

2023-09-22 09:07 UTC, TalhaMaliktz requested changes

2023-09-22 09:07 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
>  [WARNING]
**LIne 698**

The registration of the legacy validator keys has to be done **at the latest by the end of `initRounds`**, to be eligible to generate blocks in the new network.

2023-09-22 09:09 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +:lisk-migrator_darwinarm64: lisk-migrator-v2.0.0-rc.0-darwin-arm64.tar.gz
yes, I can add a todo 👍

2023-09-22 09:11 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +    "height": {snapshotHeightTestnet}
this is a variable that represents the snapshotheight for testnet

2023-09-22 09:15 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Open the `config.json` of your Lisk Core node and add a new property `backup.height` and assign it the snapshot height of the respective network.
I will add a TODO to remove this section after the `v3.1.0-rc.1` release

2023-09-22 09:21 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +.Node P2P communication
yes i see it , too, but this is an UI issue, so it's out of scope for this PR

2023-09-22 09:23 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +NOTE: Opening the ports for the node API is only mandatory, if you migrate using the `--auto-migrate-config` flag
removed it

2023-09-22 09:32 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
>  ----
I think when you first create the hashonion, you can run the command without these values, the values are only required if you import an existing hashonion. But actually I am not sure if they need to import or create a new one for the migration. @sameersubudhi can you say what is the intended approach here?

2023-09-22 09:38 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
Imho it is pretty matched, what exactly do you mean?

2023-09-22 10:19 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
It's about the values passed to the endpoint! Let's wait for what Sameer says about setting the hash onion!

2023-09-25 13:06 UTC, sameersubudhi requested changes

2023-09-25 13:06 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/management/migration.adoc
>  ----
In the CAUTION section, we can update the information about `random_setHashOnion` timing out. It doesn't timeout anymore and returns `{}` as a response (which indicates successful execution of the command) when invoked.

To verify if it was successfully set, user can execute: `random_hasHashOnion`

```bash
root@sameer-testnet-migrator-2vcpu-4gb-120gb-intel-fra1:~/lisk-core# lisk-core endpoint:invoke random_setHashOnion '{ "address": "lskbgyrx3v76jxowgkgthu9yaf3dr29wqxbtxz8yp" }'
"{}"
```

2023-09-25 13:47 UTC, TalhaMaliktz approved these changes
A couple of remarks! rest LGTM 👍🏼

2023-09-25 13:47 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
>  :snapshotHeightTestnet: 20449414
**Line 3**
I would allow more levels in the TOC for maneuverability. 
:toclevels: 4

2023-09-25 13:47 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +* maxHeightPreviouslyForged -> maxHeightGenerated
```suggestion
* `height` -> `height`
* `maxHeightPrevoted` -> `maxHeightPrevoted`
* `maxHeightPreviouslyForged` -> `maxHeightGenerated`
```

2023-09-25 15:05 UTC, sameersubudhi approved these changes
LGTM 👍

2023-09-25 15:25 UTC, shuse2 commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Alternatively, the relevant data can be obtained as well by fetching the necessary values from Lisk Service, *after the snapshot height has been reached.*
i dont think this is true. if we have to use the correct value, the value from the lisk-service could be wrong

2023-09-25 15:35 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/management/migration.adoc
> +Alternatively, the relevant data can be obtained as well by fetching the necessary values from Lisk Service, *after the snapshot height has been reached.*
I have updated the section to advice the user to use the snapshot height, but commented it out and added a todo, because it needs to be verified.

2023-09-25 15:36 UTC, shuse2 approved these changes

2023-09-25 15:39 UTC, merged