Implement download genesis block for start command
LiskHQ/lisk-core pull request #848
Opened 2023-09-21 10:18 UTC by ManuGowda

### What was the problem?

This PR resolves #846 

### How was it solved?

:recycle: Add genesis block download logic

### How was it tested?

2023-09-21 16:07 UTC, sameersubudhi commented on src/commands/start.ts
> +		network: flagParser.string({
Yes, but the default value for network in the base command is `default`. Hence, had to override it here.

2023-09-21 22:09 UTC, shuse2 requested changes

2023-09-22 07:18 UTC, shuse2 approved these changes

2023-09-22 09:16 UTC, sameersubudhi approved these changes
LGTM 👍 Works as expected 🚀

2023-09-22 09:38 UTC, Nazgolze approved these changes

2023-09-22 09:41 UTC, merged