Optimize command examples in Lisk core v4.0.0
LiskHQ/lisk-core pull request #887
Opened 2023-11-09 09:15 UTC by chris529

Closes #796

2023-11-13 11:34 UTC, chris529 commented on docs/antora/modules/ROOT/partials/core-post-installation.adoc
> +[source,jsonc]
```suggestion
[source,json]
```

2023-11-16 09:30 UTC, TalhaMaliktz requested changes
Please consider the following!

2023-11-16 09:30 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/core-cli.adoc
>    lisk-core/4.0.0 darwin-arm64 node-v18.16.0
Since all the content on this page is copied and pasted! we shouldn't change anything unless the Client CLI's content is changed by SDK. Please revert the changes to this page.

2023-11-16 09:30 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
>  i386
`arch` is the command and `i386` is its response so it should be separated.

2023-11-16 09:30 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
> + === Download and extract the binary executable
Why added a space? Does it effect formatting?
```suggestion
=== Download and extract the binary executable
```

2023-11-16 09:30 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +git checkout v4.0.0 -b v4.0.0
These are three different commands. Please separate each in its own code block.

2023-11-16 09:30 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> -
I would not remove them but would use them as caption of the aforementioned code blocks.

2023-11-16 09:30 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/source.adoc
> +// <4> Install dependencies.
Please separate each command and use the corresponding callout text as caption/description.

2023-11-16 13:52 UTC, chris529 commented on docs/antora/modules/ROOT/pages/core-cli.adoc
> +  lisk-core console [--api-ipc <value>] [--api-ws <value>]
Yes, I see your point, so it is more aligned with the Core commands as listed in the Core repo. 👍

2023-11-16 14:30 UTC, chris529 commented on docs/antora/modules/ROOT/pages/setup/binary.adoc
>  i386
Done 👍

2023-11-16 14:36 UTC, chris529 commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> -
Done 👍

2023-11-16 14:47 UTC, chris529 commented on docs/antora/modules/ROOT/pages/setup/source.adoc
> +// <4> Install dependencies.
Done 👍

2023-11-20 13:14 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/core-cli.adoc
>    lisk-core/4.0.0 darwin-arm64 node-v18.16.0
Yes, the contents on the documentation were stale. Hence, I had requested Chris to update the same.

2023-11-20 13:28 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/core-cli.adoc
>    lisk-core/4.0.0 darwin-arm64 node-v18.16.0
AFAIK If the SDK has updated the CLI reference of the client, then we should update this entire page accordingly. If not, all the changes made to this page should be reverted IMHO. Otherwise, this creates an inconsistency between docs and SDK. This is kind of a rule of thumb in docs concerning the content coming from SDK.

2023-11-20 13:41 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/core-cli.adoc
>    lisk-core/4.0.0 darwin-arm64 node-v18.16.0
Then, I'd request you to install the lisk-core v4.0.0 CLI and update the docs contents as per the console output from the command help.

2023-11-20 13:49 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/core-cli.adoc
>    lisk-core/4.0.0 darwin-arm64 node-v18.16.0
Sure, Here's the issue! https://github.com/LiskHQ/lisk-core/issues/894

2023-11-21 15:20 UTC, closed without merging