Optimize command examples in Lisk core v4.0.0
LiskHQ/lisk-core pull request #895
Opened 2023-11-21 15:24 UTC by ManuGowda

Closes https://github.com/LiskHQ/lisk-core/issues/796

2023-11-21 15:44 UTC, sameersubudhi requested changes

2023-11-21 15:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/core-cli.adoc
Haven't check the changes in this file assuming it was just copy pasted correctly from the source.

2023-11-21 15:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +cd lisk-core/docker
```suggestion
cd lisk-core
```

2023-11-21 15:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +----
```suggestion
.Check out the latest release tag
[source,bash]
----
git checkout v4.0.0
----

.Build the docker image
[source,bash]
----
make build-image
----
```

2023-11-21 15:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/source.adoc
> +cd lisk-core/docker
```suggestion
cd lisk-core
```

2023-11-21 15:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/source.adoc
> +git checkout v4.0.0 -b v4.0.0
```suggestion
git checkout v4.0.0
```

2023-11-21 15:44 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/source.adoc
> +To set up the Lisk core alias, add the following line to your `~/.profile` and run `source ~/.profile`.
```suggestion
Set up the `lisk-core` alias: Append the following line to your `~/.profile` file and run `source ~/.profile`.
```

2023-11-21 15:47 UTC, chris529 commented on docs/antora/modules/ROOT/pages/core-cli.adoc
Yes, you are correct 👍

2023-11-21 15:53 UTC, sameersubudhi approved these changes

2023-11-22 08:26 UTC, TalhaMaliktz requested changes
Please consider the following!

2023-11-22 08:26 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/core-cli.adoc
>    lisk-core/4.0.0 darwin-arm64 node-v18.16.0
- In the examples tab of each command, there is a `$` sign at the start, please remove that.
- Please also separate commands from the response, as suggested in the issue's description.

2023-11-22 08:26 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/core-cli.adoc
> +  lisk-core blockchain
I see a `$` sign at the start in some places, and in others, I don't. Do you know if this is an inconsistency from SDK?

2023-11-22 08:26 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/configuration.adoc
> +// Alternatively, enable the plugins directly in the config file, see <<using-a-custom-config-file>>.
The entire process of enabling a report misbehavior plugin has already been explained in a separate guide here: https://lisk.com/documentation/beta/run-blockchain/enabling-misbehavior-report.html

This is redundant content and will affect docs maintainability. Please remove this and simply refer to the existing guides about enabling different plugins. Just refer to the following two guides.

- https://lisk.com/documentation/beta/run-blockchain/enabling-misbehavior-report.html
- https://lisk.com/documentation/beta/build-blockchain/using-dashboard.html

2023-11-22 08:26 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +.Navigate into the `lisk-core` root folder
There is an issue with rendering monospace in captions, please either use quotation marks or write without them.
```suggestion
.Navigate into the "lisk-core" root folder
```

2023-11-22 08:26 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/source.adoc
> +.Navigate into the `lisk-core` root folder
```suggestion
.Navigate into the "lisk-core" root folder
```

2023-11-22 11:35 UTC, chris529 commented on docs/antora/modules/ROOT/pages/core-cli.adoc
>    lisk-core/4.0.0 darwin-arm64 node-v18.16.0
Done 👍

2023-11-22 11:36 UTC, chris529 commented on docs/antora/modules/ROOT/pages/core-cli.adoc
> +  lisk-core blockchain
Now all descriptions (USAGE), start with the $ sign to maintain uniformity throughout the page 👍

2023-11-22 16:38 UTC, chris529 commented on docs/antora/modules/ROOT/pages/management/configuration.adoc
> +// Alternatively, enable the plugins directly in the config file, see <<using-a-custom-config-file>>.
Good point..now done 👍

2023-11-23 12:39 UTC, TalhaMaliktz approved these changes
Just a small addition required! rest LGTM 👍🏼

2023-11-23 12:39 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/core-cli.adoc
**Line 8**
`:source-language: bash`

2023-11-23 13:42 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/source.adoc
> +----
```suggestion
Set up the `lisk-core` alias: Append the following line to your `~/.profile` file and run `source ~/.profile`.
[source,bash]
----
alias lisk-core=/home/lisk/lisk-core/bin/run
----
NOTE: In the command above, please replace `/home/lisk/lisk-core` with the absolute path to your "lisk-core" directory. To find the exact path on your system, change to your lisk-core directory and run the `pwd` command.
```

2023-11-23 15:52 UTC, merged